config/routes.rb
Rails.application.routes.draw do
  resources :animals do
    resources :sightings
  end

  resources :regions do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  validates :name, :locality, :enemy, presence: true

  has_many :sightings
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :sightings
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  validates :location, :longitude, :latitude, :date, presence: true

  belongs_to :animal
  belongs_to :region

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    render :index
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

  def new
    @animal = Animal.new
    render :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animal_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

private
  def animal_params
    params.require(:animal).permit(:name, :locality, :enemy)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  

end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def show
    @sighting = Sighting.find(params[:id])
    @region = @sighting.region.name
    render :show
  end

  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@sighting.animal)
    else
      render :new
    end
  end

  def edit
    @sighting = Sighting.find(params[:id])
    @animal = @sighting.animal
    render :edit
  end

  def update
    @sighting = Sighting.find(params[:id])
    @animal = @sighting.animal
    if @sighting.update(sighting_params)
      redirect_to animal_path(@animal)
    else
      render :edit
    end
  end

  def destroy
    sighting = Sighting.find(params[:id])
    animal = sighting.animal
    sighting.destroy
    redirect_to animal_path(animal)
  end

private
  def sighting_params
    params.require(:sighting).permit(:location, :longitude, :latitude, :date, :region_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= render "layouts/errors", :object => @animal%>

<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :locality %>
  <%= f.text_field :locality %>
  <%= f.label :enemy %>
  <%= f.text_field :enemy %>
  <%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h1>EDIT THAT ANIMAL</h1>

<%= render 'form' %>

app/views/animals/index.html.erb
<h1>Animals R Us</h1>

<%= link_to "New Animal", new_animal_path %>

<ul>
  <% @animals.each do |animal| %>
    <li><%= link_to animal.name, animal_path(animal) %></li>
  <% end %>
</ul>

app/views/animals/new.html.erb
<h1>ADD A NEW ONE</h1>

<%= render "form" %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>
<h3><em><%= @animal.locality %></em></h3>
<h3>Mortal enemies with <%= @animal.enemy %></h3>

<%= link_to 'Add a Sighting', new_animal_sighting_path(@animal) %>

<% if @animal.sightings.any? %>
  <p>THIS ANIMAL IS EVERYWHERE</p>

  <ul>
    <% @animal.sightings.each do |sighting| %>
      <li><%= link_to "#{sighting.location} -- #{sighting.date.to_formatted_s(:long)}", animal_sighting_path(@animal, sighting) %></li>
    <% end %>
  </ul>
<% else %>
  <p>It's hiding...</p>
<% end %>

<%= link_to "Edit", edit_animal_path(@animal) %>
<%= link_to "Home", animals_path %>
<%= link_to "Delete Animal", animal_path(@animal),
                            :data => { confirm: "Are you sure",
                            :method => 'delete'} %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>YOU LIE!</h3>

  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= render 'layouts/errors', :object => @sighting %>

<%= form_for [@animal, @sighting] do |f| %>
  <%= f.label 'Location' %>
  <%= f.text_field :location %>
  <%= f.label 'Longitude' %>
  <%= f.text_field :longitude %>
  <%= f.label 'Latitude' %>
  <%= f.text_field :latitude %>
  <%= f.label 'Date' %>
  <%= f.date_field :date %>
  <%= f.collection_select(:region_id, Region.all, :id, :name) %>
  <%= f.submit %>
<% end %>

app/views/sightings/edit.html.erb
<h1>EDIT THIS</h1>

<%= render "form" %>

app/views/sightings/new.html.erb
<h1>New Sighting of a <%= @animal.name %>!</h1>

<%= render 'form' %>

app/views/sightings/show.html.erb
<h1><%= @sighting.location %></h1>
<h4>Coordinates : <%= @sighting.longitude %> - <%= @sighting.latitude %></h4>
<h4>When? - <%= @sighting.date.to_formatted_s(:long) %></h4>
<h4>Where? - <%= @region %></h4>
<%= link_to "Edit", edit_animal_sighting_path %>
<%= link_to "Delete", animal_sighting_path(@sighting.animal, @sighting), :data => {:confirm => "Are Your Sure?", :method => "delete"} %>